module.exports = [
    "What was the last thing you ate?",
    "What is your most controversial movie opinion?\nReminder: no politics :)",
    "What is your favorite food?",
    "Is water wet?",
    "What is your dream car?\n(Not the movie)",
    "Which Star Wars droid is your favorite? Why?",
    "If you were a Fruit of the Spirit, which one would you be and why?",
    "What is your favourite Bible verse/book/character?",
    "Which <#1062596224844308510> member[s] should run in the next Presidential election? Why?",
    "Which day of the week is superior to all others?",
    "If you were an element, which one would you be? Why?",
    "What is the best way to start a day?",
    "Why is the rum gone?",
    "C-3PO and I recently bought a pet Loth Cat. What should we name it?",
    "Which spaceship has the coolest design?",
    "What musical instrument is rarely played but is actually awesome?",
    "What is the first thing you want to say to Jesus when you meet Him in person?",
    "How many seconds do you microwave your tea for?",
    "Someone pick a movie, then everyone help recast the characters using Star Wars characters.",
    "What's your favorite means of communication and why?",
    "I'm building an ark, but it can only fit 10 different animals. Which ones get to come aboard?",
    "What is the best species in Star Wars and why?",
    "Someone pick a movie, then everyone help recast the characters using muppets.",
    "Who's your favorite superhero?",
    "If your personality was a food, what food would you be? Why?",
    "It you were a plant, what plant would you be? Why?",
    "What's one fun animal fact that you know?",
]
