// Array of questions for the would you rather game

module.exports = [
  ["Be a Jedi", "Be a Sith"],
  ["Eat pie", "Eat cake"],
  ["Spam in the Cantina", "Make a thread like civilised beings"],
  ["Be a Clone Trooper", "Be a Storm Trooper"],
  ["Be a part of the Republic", "Be a part of the Separatist Alliance"],
  ["Be Cad Bane", "Be Boba Fett"],
  ["Be Hondo Onaka", "Be Jack Sparrow"],
  ["Live in a treehouse", "Live in a cave"],
  ["Be loved", "Be feared"],
  ["Send a :carrot: for xp", "Send a :wolf: for xp"],
  ["Be a Jedi", "Be a Mandolorian"],
  ["Eat a pizza", "Eat some tacos"],
  ["Have the ability to fly", "Have the ability to rewind time"],
  ["Marvel Comics", "DC Comics"],
  ["Marvel Heroes", "DC Heroes"],
  ["Marvel Movies", "DC Movies"],
  ["Only be able to speak like yoda", "Only be able to speak in a foreign language"],
  ["Thrawn", "Plo Koon"],
  ["Read fiction", "Read non-fiction"],
  ["Pirate :potato:", "Potato :pirate_flag:"],
  ["Join the Avengers", "Join the Justice League"],
  ["Star Wars: The Clone Wars", "Star Wars: Rebels"],
  ["Star Wars Prequel Trilogy", "Star Wars Sequel Trilogy"],
  ["Americans", "Brits"],
  ["Time Travel to meet the 1st President", "Time Travel to meet the 100th president"],
  ["Fantasy football", "Football in fantasy"],
  ["Star Wars Legends", "Star Wars Canon"],
  ["Toby Maguire Spiderman", "Andrew Garfield Spiderman"],
  ["Visit the Star Wars universe", "Visit the Lord of The Rings Universe"],
  ["Bears", "Beets"],
  ["Master Hand", "Crazy Hand"],
  ["Be Star Lord", "Be Thor"],
  ["Star Wars", "Star Trek"],
  ["Wield the Darksaber", "Wield the Master Sword"],
  ["Voltron", "Power Rangers"],
  ["Apples", "Bananas"],
  ["Super Smash Bros.", "Mario Kart"],
  ["Never eat pizza again", "Always eat pizza themed food for every meal"],
  ["Only play Star Wars Battlefront II (2005) ever again", "Only play Republic Commandos ever again"],
  ["Join the Bad Batch", "Join Ghost Squadron"],
  
  
  
]
